[clarify.bstr]
version = "=1"
expression = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
license-files = [
    { path = "COPYING", hash = 0x278afbcf },
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0x462dee44 },
    { path = "src/unicode/data/LICENSE-UNICODE", hash = 0x70f7339 },
]

[clarify."bzip2-sys"]
expression = "(MIT OR Apache-2.0) AND bzip2-1.0.6"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0x9374b940 },
    { path = "bzip2-1.0.8/LICENSE", hash = 0x71e74485 },
]

[clarify.crossbeam-channel]
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0xbc436f08 },
    { path = "LICENSE-THIRD-PARTY", hash = 0x847bf39 },
]

[clarify.exr]
expression = "BSD-3-Clause"
license-files = [
    { path = "LICENSE.md", hash = 0x633bbc5d },
]

[clarify.half]
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE", hash = 0xa9f8b3a2 },
]

[clarify.lzma-sys]
expression = "(MIT OR Apache-2.0) AND LicenseRef-scancode-lzma-sdk-pd"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0x502274a5 },
    { path = "xz-5.2/COPYING", hash = 0x282fd28 },
]
skip-files = [
    "xz-5.2/COPYING.GPLv2",
    "xz-5.2/COPYING.GPLv3",
    "xz-5.2/COPYING.LGPLv2.1",
]

[clarify.petgraph]
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0xc97e30bd },
]
skip-files = [
    # this license applies to graphical assets which we do not distribute
    "assets/LICENSE.md",
]

[clarify.regex-syntax]
expression = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x24b54f4b },
    { path = "LICENSE-MIT", hash = 0xb755395b },
    { path = "src/unicode_tables/LICENSE-UNICODE", hash = 0xa7f28b93 },
]

[clarify.typenum]
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE-APACHE", hash = 0x91d5a0a7 },
    { path = "LICENSE-MIT", hash = 0xb9f15462 },
    { path = "LICENSE", hash = 0xa4618a29 },
]

[clarify.unicode-ident]
expression = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
license-files = [
    { path = "LICENSE-APACHE", hash = 0xb5518783 },
    { path = "LICENSE-MIT", hash = 0x386ca1bc },
    { path = "LICENSE-UNICODE", hash = 0x9698cbbe },
]

[clarify.zstd-safe]
# zstd-safe is MIT OR Apache-2.0
expression = "MIT OR Apache-2.0"
license-files = [
    { path = "LICENSE", hash = 0x742401ae },
    { path = "LICENSE.Apache-2.0", hash = 0x7b466be4 },
    { path = "LICENSE.Mit", hash = 0xa237d234 },
]
skip-files = [
    "zstd/COPYING", # copy of the GPLv2 we are not choosing from libzstd's dual license
    "zstd/build/LICENSE", # empty file
    "zstd/contrib/linux-kernel/COPYING", # kernel source and patches for adding zstd (?!), not used
]

[clarify.zstd-sys]
# zstd-sys is MIT OR Apache-2.0
# libzstd is GPL-2.0-only OR BSD-3-Clause (selecting BSD-3-Clause)
expression = "(MIT OR Apache-2.0) AND BSD-3-Clause"
license-files = [
    { path = "LICENSE", hash = 0x742401ae },
    { path = "LICENSE.Apache-2.0", hash = 0x7b466be4 },
    { path = "LICENSE.Mit", hash = 0xa237d234 },
    { path = "LICENSE.BSD-3-Clause", hash = 0xc9f5c4f6 },
    { path = "zstd/LICENSE", hash = 0x3bfe1fb1 },
]
skip-files = [
    "zstd/COPYING", # copy of the GPLv2 we are not choosing from libzstd's dual license
    "zstd/build/LICENSE", # empty file
    "zstd/contrib/linux-kernel/COPYING", # kernel source and patches for adding zstd (?!), not used
]
