[package]
name = "pipesys"
version = "0.1.0"
authors = ["Ben Cressey <bcressey@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
bincode.workspace = true
clap = { workspace = true, features = ["derive"] }
daemonize.workspace = true
env_logger.workspace = true
futures.workspace = true
log.workspace = true
nix = { workspace = true, features = ["fs"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["fs", "macros", "rt-multi-thread"] }

[target.'cfg(target_os = "linux")'.dependencies]
inotify.workspace = true
uds = { workspace = true, features = ["tokio"] }
